on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  down:
    name: Destroy ephemeral environment
    runs-on: ubuntu-latest

    environment:
      name: preview

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    env:
      AWS_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-action-branch-box
      TF_BACKEND_S3_BUCKET: tf-state-branch-box-${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment name
        run: |
          environment=${GITHUB_HEAD_REF##*/}
          echo "ENVIRONMENT=${environment}" >> $GITHUB_ENV

      - name: Assume AWS IAM role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE }}

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0
          terraform_wrapper: false

      - name: Dispose of ephemeral environment
        working-directory: ./infra
        run: |
          terraform init \
            -backend-config="bucket=${TF_BACKEND_S3_BUCKET}" \
            -backend-config="key=${ENVIRONMENT}.tfstate"

          terraform destroy -auto-approve \
            -var="name=${{ github.event.repository.name }}" \
            -var="environment=${ENVIRONMENT}" \
            -var="image_tag=${GITHUB_SHA}"

      - name: Add PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message: PR environment successfully destroyed
          allow-repeats: false
