on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, edited]
    paths-ignore:
      - "**/*.md"

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.4"

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Verify formatting
        run: |
          set -euo pipefail

          make fmt

          DIFF=$(git status --porcelain)

          if [ -n "$DIFF" ]; then
            echo "These files were modified:"
            echo
            echo "$DIFF"
            echo
            exit 1
          fi

  up:
    name: Deploy PR to ephemeral environment
    runs-on: ubuntu-latest
    needs: [test]

    environment:
      name: preview
      url: ${{ steps.deploy.outputs.URL }}

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    env:
      AWS_REGION: eu-north-1
      AWS_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-action-branch-box
      TF_BACKEND_S3_BUCKET: tf-state-branch-box-${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment name
        run: |
          environment=${GITHUB_HEAD_REF##*/}
          echo "ENVIRONMENT=${environment}" >> $GITHUB_ENV

      - name: Assume AWS IAM role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE }}

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.9

      - name: Lambda-ify
        run: echo "COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.7.1 /lambda-adapter /opt/extensions/lambda-adapter" >> Dockerfile

      - name: Deploy to ephemeral environment
        id: deploy
        working-directory: ./terraform
        run: |
          terraform init \
            -backend-config="bucket=${TF_BACKEND_S3_BUCKET}" \
            -backend-config="key=${ENVIRONMENT}.tfstate"

          terraform apply -auto-approve \
            -var="name=${{ github.event.repository.name }}" \
            -var="environment=${ENVIRONMENT}" \
            -var="image_tag=${GITHUB_SHA}"

          echo "URL=$(terraform output -json | jq '.endpoint_url.value' -r)" >> $GITHUB_OUTPUT

      - name: Add HTTPS endpoint to PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            :rocket: Code successfully deployed to a new ephemeral containerized PR environment!

            ${{ steps.deploy.outputs.URL }}
          allow-repeats: true
